### testing
POST http://localhost:8080/flight-query
Content-Type: application/json

{
  "query": {
    "market": "US",
    "locale": "en-US",
    "currency": "USD",
    "queryLegs": [
      {
        "originPlaceId": {
          "iata": "JFK"
        },
        "destinationPlaceId": {
        "iata": "PSP"
      },
        "date": {
          "year": 2023,
          "month": 5,
          "day": 20
        }
      }
    ],
    "cabinClass": "CABIN_CLASS_ECONOMY",

    "adults": 1
  }
}